### ISSUE TITLE
Prepend option for `insert.css`

### ISSUE THREAD

**Issue by BigBlueHat** [wankdanker/jsinclude#1]
First, thanks for building this script! I've found it very helpful while building [BlueInk](http://github.com/bigbluehat/blueink).

One thing that's missing, is pre-pending (vs. appending) CSS files to the `<head>` tag.

The [insert-css](https://github.com/substack/insert-css) library has this:
https://github.com/substack/insert-css/commit/760d7f536520fef7fc703ae9bfefc8b52537f340

Should be a simple add. :smile: 

Thanks!

**Comment by BigBlueHat** [comment]
Boom! Amazing! :smile_cat: 

Much thanks @wankdanker 

/me upgrades

**Comment by wankdanker** [comment]
Cool! I'm glad to hear that someone has found this module useful!

I pushed out a small change to add support for this request similar to how substack did it. Thank you for that reference.

Try it out and let me know if you have any issues.

jsinclude@1.1.0 on npm.
